ch02_number_quiz/src/java/com/corejsf/ProblemBean.java
package com.corejsf;

import java.io.Serializable;
import java.util.ArrayList;

public class ProblemBean implements Serializable {
   private ArrayList<Integer> sequence; 
   private int solution;
   
   public ProblemBean() {}

   public ProblemBean(int[] values, int solution) {
      sequence = new ArrayList<Integer>();
      for (int i = 0; i < values.length; i++)
         sequence.add(values[i]);
      this.solution = solution;
   }

   public ArrayList<Integer> getSequence() { return sequence; }
   public void setSequence(ArrayList<Integer> newValue) { sequence = newValue; }

   public int getSolution() { return solution; }
   public void setSolution(int newValue) { solution = newValue; }
}

ch02_number_quiz/src/java/com/corejsf/QuizBean.java
package com.corejsf;

import java.io.Serializable;
import java.util.ArrayList;

import javax.inject.Named; 
   // or import javax.faces.bean.ManagedBean;
import javax.enterprise.context.SessionScoped; 
   // or import javax.faces.bean.SessionScoped;

@Named // or @ManagedBean
@SessionScoped
public class QuizBean implements Serializable {
   private ArrayList<ProblemBean> problems = new ArrayList<ProblemBean>();     
   private int currentIndex;
   private int score;
   
   public QuizBean() {      
      problems.add(
         new ProblemBean(new int[] { 3, 1, 4, 1, 5 }, 9)); // pi
      problems.add(
         new ProblemBean(new int[] { 1, 1, 2, 3, 5 }, 8)); // fibonacci
      problems.add(
         new ProblemBean(new int[] { 1, 4, 9, 16, 25 }, 36)); // squares
      problems.add(
         new ProblemBean(new int[] { 2, 3, 5, 7, 11 }, 13)); // primes
      problems.add(
         new ProblemBean(new int[] { 1, 2, 4, 8, 16 }, 32)); // powers of 2
   }   

   public void setProblems(ArrayList<ProblemBean> newValue) { 
      problems = newValue;
      currentIndex = 0;
      score = 0;
   } 
      
   public int getScore() { return score; }

   public ProblemBean getCurrent() { return problems.get(currentIndex); }

   public String getAnswer() { return ""; }
   public void setAnswer(String newValue) { 
      try {
         int answer = Integer.parseInt(newValue.trim());
         if (getCurrent().getSolution() == answer) score++;            
         currentIndex = (currentIndex + 1) % problems.size();
      }
      catch (NumberFormatException ex) {
      }
   }   
}

ch02_number_quiz/web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
   <h:head>
      <title>#{msgs.title}</title>
   </h:head>
   <h:body>
      <h:form>
         <h3>#{msgs.heading}</h3>
         <p>
            <h:outputFormat value="#{msgs.currentScore}">
               <f:param value="#{quizBean.score}"/>
            </h:outputFormat>
         </p>
         <p>#{msgs.guessNext}</p>
         <p>#{quizBean.current.sequence}</p>
         <p>
            #{msgs.answer}
            <h:inputText value="#{quizBean.answer}"/>
         </p>
         <p><h:commandButton value="#{msgs.next}"/></p>
      </h:form>
   </h:body>
</html>